READ_STEP = 2
ANGLE_WINDOW_LEN = 30
CALCULATION_STEP = ANGLE_WINDOW_LEN * 3
SPIN_BUFFER_SIZE = 3
# The close to accurate is 1/4. The most accurate 1/3.
MIN_SKIP_OF_WHEEL_SPIN = 1 / 3
MIN_SKIP_SEC = 10
MAX_MEAN_ANGLE_DELTA = 10.0
TESSERACT_LANG = "rus+eng" # "eng"

NASTY_OPTIMIZATION = True

SPIN_DETECT_LENGTH = True
SPIN_BUFFER_SIZE_FOR_LENGTH_DETECTION = 10
FRAMES_STEP_FOR_LENGTH_DETECTION = 10
LOOK_BEHIND_FRAMES_FOR_LENGTH_DETECTION = 5
EXCLUDE_SECONDS_RANGE = (30, 180)
ASK_LENGTH = True


VISUALIZATION_ENABLED = False
