READ_STEP = 2
ANGLE_WINDOW_SIZE = 30
CALCULATION_STEP = ANGLE_WINDOW_SIZE * 3
SPIN_BUFFER_SIZE = 3
# The calculations are most accurate at 1/3 and fairly accurate at 1/4.
MIN_WHEEL_SPIN_SKIP_RATIO = 1 / 3
MIN_SKIP_DURATION = 10
MAX_ANGLE_DELTA = 10.0

TESSERACT_LANGUAGE = "rus+eng"  # "eng"

SPECULATIVE_OPTIMIZATION = True

DURATION_DETECTION_MAX_SPINS = 10
DURATION_DETECTION_MAX_FRAMES = 600
DURATION_DETECTION_FRAME_STEP = 10
DURATION_DETECTION_TIME_RANGE = (30, 180)

PROMPT_FOR_DURATION = True

VISUALIZATION_ENABLED = False
