name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        sudo apt-get update && sudo apt-get install -y python3-opencv tesseract-ocr libtesseract-dev libleptonica-dev
        pip install -r requirements.txt

    - name: Verify installation
      run: |
        python -c "import cv2; import pytesseract; print(cv2.__version__); print(pytesseract.get_tesseract_version())"

    - name: Run Black
      run: |
        pip install black
        black --check .

#    - name: Run tests
#      run: |
#        python -m unittest discover -s tests -t .
